## GATEWAY CONFIG
spring:
  application:
    name: core-gateway
  cloud:
    gateway:
      routes:
#        USER SERVICE
        - id: core-user-service
          uri: lb://core-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
#          TRF SERVICE
        - id: core-wallet-service
          uri: lb://core-wallet-service
          predicates:
            - Path=/wallet/**
          filters:
            - StripPrefix=1
#          NOTIF REPORT SERVICE
        - id: core-report-service
          uri: lb://core-report-service
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
#          PARAMETER SERVICE
        - id: core-parameter-service
          uri: lb://core-parameter-service
          predicates:
            - Path=/parameter/**
          filters:
            - StripPrefix=1
#          AUDIT SERVICE
        - id: core-audit-service
          uri: lb://core-audit-service
          predicates:
            - Path=/audit/**
          filters:
            - StripPrefix=1
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
